version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: unolingo-db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "npx prisma migrate deploy && yarn prisma:seed && yarn start:prod"
    image: app:latest
    container_name: nestjs-app
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty123@db:5432/unolingo-db?schema=public
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
