import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
	await prisma.$connect()
	if (process.env.SEED_DATABASE !== 'true') return
	try {
		console.log('Starting database seeding...')

		await prisma.$transaction(async prisma => {
			await prisma.language.createMany({
				data: [
					{
						name: 'Английский',
						sourceLang: 'RU',
						targetLang: 'EN',
						flagIcon: '/img/english-flag.png',
						id: 1,
					},
					{
						name: 'Немецкий',
						sourceLang: 'RU',
						targetLang: 'DE',
						flagIcon: '/img/deutsch-flag.png',
						id: 2,
					},
					{
						name: 'Французский',
						sourceLang: 'RU',
						targetLang: 'FR',
						flagIcon: '/img/french-flag.png',
						id: 3,
					},
					{
						name: 'Deutsch',
						sourceLang: 'EN',
						targetLang: 'DE',
						flagIcon: '/img/deutsch-flag.png',
						id: 4,
					},
				],
			})
			await prisma.section.createMany({
				data: [
					{ languageId: 1, name: 'Present Simple', order: 1, id: 1 },
					{ languageId: 1, name: 'Past Simple', order: 2, id: 2 },
					{ languageId: 1, name: 'Future Simple', order: 3, id: 3 },
					{ languageId: 2, name: 'Präsens', order: 1, id: 4 },
					{ languageId: 2, name: 'Präteritum', order: 2, id: 5 },
					{ languageId: 3, name: 'Présent', order: 1, id: 6 },
					{ languageId: 4, name: 'Präsens', order: 1, id: 7 },
				],
			})
			await prisma.theory.createMany({
				data: [
					{
						sectionId: 1,
						title: 'Present Simple',
						paragraphs: [
							{
								title: 'Когда используется:',
								items: [
									'Для регулярных действий (I work every day)',
									'Для общеизвестных фактов (Water boils at 100°C)',
									'Для постоянных состояний (He lives in London)',
								],
							},
							{
								title: 'Правила построения:',
								items: [
									'Утверждение: Subject + V/Vs (She works)',
									"Отрицание: do/does + not + V (I don't work)",
									'Вопрос: Do/Does + subject + V? (Do you work?)',
								],
							},
							{
								title: 'Примеры:',
								items: [
									'Я говорю → I speak',
									"Она не играет → She doesn't play",
									'Ты работаешь? → Do you work?',
								],
							},
						],
					},
					// Past Simple (RU → EN)
					{
						sectionId: 2,
						title: 'Past Simple',
						paragraphs: [
							{
								title: 'Когда используется:',
								items: [
									'Завершённые действия в прошлом (I saw him yesterday)',
									'Последовательность событий (I came, I saw, I conquered)',
								],
							},
							{
								title: 'Правила:',
								items: [
									'Правильные глаголы: V + ed (worked)',
									'Неправильные глаголы: 2-я форма (see → saw)',
									"Отрицание: did + not + V (I didn't go)",
									'Вопрос: Did + subject + V? (Did you eat?)',
								],
							},
							{
								title: 'Примеры:',
								items: [
									'Я работал → I worked',
									"Она не пришла → She didn't come",
									'Ты видел? → Did you see?',
								],
							},
						],
					},
					// Future Simple (RU → EN)
					{
						sectionId: 3,
						title: 'Future Simple',
						paragraphs: [
							{
								title: 'Когда используется:',
								items: [
									"Спонтанные решения (I'll answer the phone)",
									'Прогнозы (It will rain tomorrow)',
									"Обещания (I'll call you later)",
								],
							},
							{
								title: 'Правила:',
								items: [
									'Утверждение: will + V (I will go)',
									"Отрицание: will + not + V (I won't tell)",
									'Вопрос: Will + subject + V? (Will you help?)',
								],
							},
							{
								title: 'Примеры:',
								items: [
									'Я сделаю → I will do',
									"Она не придёт → She won't come",
									'Ты поможешь? → Will you help?',
								],
							},
						],
					},
					// Präsens (RU → DE)
					{
						sectionId: 4,
						title: 'Präsens',
						paragraphs: [
							{
								title: 'Когда используется:',
								items: [
									'Регулярные действия (Ich arbeite → Я работаю)',
									'Общие факты (Wasser kocht bei 100°C → Вода кипит при 100°C)',
								],
							},
							{
								title: 'Правила спряжения:',
								items: [
									'ich: -e (arbeite)',
									'du: -st (arbeitest)',
									'er/sie/es: -t (arbeitet)',
									'wir/sie/Sie: -en (arbeiten)',
								],
							},
							{
								title: 'Примеры:',
								items: [
									'Я учу → Ich lerne',
									'Ты играешь → Du spielst',
									'Он работает → Er arbeitet',
								],
							},
						],
					},
					// Präteritum (RU → DE)
					{
						sectionId: 5,
						title: 'Präteritum',
						paragraphs: [
							{
								title: 'Когда используется:',
								items: [
									'Письменная речь/рассказы (Es war einmal...)',
									'Прошедшие события (Ich ging gestern ins Kino)',
								],
							},
							{
								title: 'Правила:',
								items: [
									'Слабые глаголы: корень + -te (ich lernte)',
									'Сильные глаголы: изменение корня (gehen → ging)',
									'Отрицание: nicht + глагол (Ich ging nicht)',
								],
							},
							{
								title: 'Примеры:',
								items: [
									'Я учил → Ich lernte',
									'Она пришла → Sie kam',
									'Мы не видели → Wir sahen nicht',
								],
							},
						],
					},
					// Présent (RU → FR)
					{
						sectionId: 6,
						title: 'Présent',
						paragraphs: [
							{
								title: 'When used:',
								items: [
									'For actions happening now (Je mange → Я ем прямо сейчас)',
									'For habits (Je vais au travail → Я хожу на работу)',
									'For general truths (Paris est en France → Париж находится во Франции)',
								],
							},
							{
								title: 'Verb conjugation rules:',
								items: [
									'-ER verbs (parler): je parle, tu parles, il/elle parle, nous parlons, vous parlez, ils/elles parlent',
									'-IR verbs (finir): je finis, tu finis, il/elle finit, nous finissons, vous finissez, ils/elles finissent',
									'-RE verbs (vendre): je vends, tu vends, il/elle vend, nous vendons, vous vendez, ils/elles vendent',
								],
							},
							{
								title: 'Negation rules:',
								items: [
									'Basic structure: ne + verb + pas (Je ne parle pas → Я не говорю)',
									"With vowels: n' + verb + pas (Je n'aime pas → Я не люблю)",
								],
							},
							{
								title: 'Question formation:',
								items: [
									'Inversion: Parles-tu français? (Ты говоришь по-французски?)',
									'With "Est-ce que": Est-ce que tu parles français?',
									'Intonation: Tu parles français? (spoken)',
								],
							},
							{
								title: 'Common irregular verbs:',
								items: [
									'Être (to be): je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont',
									"Avoir (to have): j'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont",
									'Aller (to go): je vais, tu vas, il/elle va, nous allons, vous allez, ils/elles vont',
								],
							},
							{
								title: 'Sample sentences:',
								items: [
									'I speak → Je parle',
									'You (singular) eat → Tu manges',
									'We live → Nous habitons',
									"They don't understand → Ils ne comprennent pas",
									'Do you work? → Travaillez-vous?',
								],
							},
						],
					},
					// Präsens (EN → DE)
					{
						sectionId: 7,
						title: 'Präsens',
						paragraphs: [
							{
								title: 'When used:',
								items: [
									'For regular actions (I work → Ich arbeite)',
									'General facts (Cats eat fish → Katzen essen Fisch)',
								],
							},
							{
								title: 'Conjugation rules:',
								items: [
									'ich: -e (lerne)',
									'du: -st (lernst)',
									'er/sie/es: -t (lernt)',
									'wir/sie/Sie: -en (lernen)',
								],
							},
							{
								title: 'Sample sentences:',
								items: ['I learn → Ich lerne', 'You speak → Du sprichst', 'He works → Er arbeitet'],
							},
						],
					},
				],
			})
			await prisma.level.createMany({
				data: [
					// SECTION PRESENT SIMPLE RU EN
					{ sectionId: 1, order: 1, id: 1 },
					{ sectionId: 1, order: 2, id: 2 },
					{ sectionId: 1, order: 3, id: 3 },
					{ sectionId: 1, order: 4, id: 4 },
					{ sectionId: 1, order: 5, id: 5 },
					// SECTION PAST SIMPLE RU EN
					{ sectionId: 2, order: 1, id: 6 },
					{ sectionId: 2, order: 2, id: 7 },
					{ sectionId: 2, order: 3, id: 8 },
					{ sectionId: 2, order: 4, id: 9 },
					{ sectionId: 2, order: 5, id: 10 },
					// SECTION FUTURE SIMPLE RU EN
					{ sectionId: 3, order: 1, id: 11 },
					{ sectionId: 3, order: 2, id: 12 },
					{ sectionId: 3, order: 3, id: 13 },
					{ sectionId: 3, order: 4, id: 14 },
					{ sectionId: 3, order: 5, id: 15 },
					// SECTION Präsens RU GE
					{ sectionId: 4, order: 1, id: 16 },
					{ sectionId: 4, order: 2, id: 17 },
					{ sectionId: 4, order: 3, id: 18 },
					{ sectionId: 4, order: 4, id: 19 },
					{ sectionId: 4, order: 5, id: 20 },
					// SECTION Präteritum RU GE
					{ sectionId: 5, order: 1, id: 21 },
					{ sectionId: 5, order: 2, id: 22 },
					{ sectionId: 5, order: 3, id: 23 },
					{ sectionId: 5, order: 4, id: 24 },
					{ sectionId: 5, order: 5, id: 25 },
					// SECTION Présent RU FR
					{ sectionId: 6, order: 1, id: 26 },
					{ sectionId: 6, order: 2, id: 27 },
					{ sectionId: 6, order: 3, id: 28 },
					{ sectionId: 6, order: 4, id: 29 },
					{ sectionId: 6, order: 5, id: 30 },
					// SECTION Präsens EN GE
					{ sectionId: 7, order: 1, id: 31 },
					{ sectionId: 7, order: 2, id: 32 },
					{ sectionId: 7, order: 3, id: 33 },
					{ sectionId: 7, order: 4, id: 34 },
					{ sectionId: 7, order: 5, id: 35 },
				],
			})
			await prisma.task.createMany({
				data: [
					// SECTION PRESENT SIMPLE RU EN
					{
						id: 1,
						levelId: 1,
						type: 'WORD_PICKER',
						question: 'Я учу английский язык',
						correctAnswer: 'I study English',
						options: ['study', 'I', 'English'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 2,
						levelId: 1,
						type: 'TEXT_INPUT',
						question: 'Мы играем на скрипках',
						correctAnswer: 'We play the violins',
						options: [],
						partialAnswer: ['We', 'the violins'],
						order: 2,
					},
					{
						id: 3,
						levelId: 1,
						type: 'WORD_PICKER',
						question: 'Кошкам нравится молоко',
						correctAnswer: 'Cats like milk',
						options: ['milk', 'like', 'Cats'],
						partialAnswer: [],
						order: 3,
					},
					{
						id: 4,
						levelId: 2,
						type: 'WORD_PICKER',
						question: 'Я не говорю по-английски',
						correctAnswer: 'I do not speak English',
						options: ['speak', 'not', 'English', 'do', 'I'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 5,
						levelId: 2,
						type: 'TEXT_INPUT',
						question: 'Никто не говорит на латыни',
						correctAnswer: 'Nobody speaks Latin',
						options: [],
						partialAnswer: ['Nobody', 'Latin'],
						order: 2,
					},
					{
						id: 6,
						levelId: 2,
						type: 'WORD_PICKER',
						question: 'Моя собака не любит кошек',
						correctAnswer: "My dog doesn't like cats",
						options: ['dog', 'doesn', 'My', "'t", 'cats', 'like'],
						partialAnswer: [],
						order: 3,
					},
					{
						id: 7,
						levelId: 3,
						type: 'WORD_PICKER',
						question: 'Кот Саймона не любит плавать',
						correctAnswer: "Simon's cat doesn't like to swim",
						options: ['cat', 'doesn', 'Simon', "'t", "'s", 'swim', 'to', 'like'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 8,
						levelId: 3,
						type: 'TEXT_INPUT',
						question: 'Ты говоришь по-английски?',
						correctAnswer: 'Do you speak English?',
						options: [],
						partialAnswer: ['', 'English?'],
						order: 2,
					},
					{
						id: 9,
						levelId: 4,
						type: 'WORD_PICKER',
						question: 'Кот Саймона любит плавать?',
						correctAnswer: "Does Simon's cat like to swim?",
						options: ['cat', 'Does', 'Simon', "'s", 'swim?', 'to', 'like'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 10,
						levelId: 4,
						type: 'WORD_PICKER',
						question: 'Где она играет на скрипке?',
						correctAnswer: 'Where does she play the violin?',
						options: ['does', 'violin?', 'Where', 'play', 'the', 'she'],
						partialAnswer: [],
						order: 2,
					},
					{
						id: 11,
						levelId: 5,
						type: 'WORD_PICKER',
						question: 'Медицинские записи конфиденциальны',
						correctAnswer: 'Medical records are confidential',
						options: ['records', 'are', 'Medical', 'confidential'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 12,
						levelId: 5,
						type: 'WORD_PICKER',
						question: 'Это ваше первое заявление на поступление в колледж?',
						correctAnswer: 'Is this your first application to college?',
						options: ['your', 'Is', 'first', 'application', 'this', 'college?', 'to'],
						partialAnswer: [],
						order: 2,
					},
					// SECTION PAST SIMPLE RU EN
					{
						id: 13,
						levelId: 6,
						type: 'WORD_PICKER',
						question: 'Она работала за границей',
						correctAnswer: 'She worked abroad',
						options: ['worked', 'abroad', 'She'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 14,
						levelId: 6,
						type: 'TEXT_INPUT',
						question: 'Гарри написал много книг',
						correctAnswer: 'Harry wrote a lot of books',
						options: [],
						partialAnswer: ['Harry', 'of books'],
						order: 2,
					},
					{
						id: 15,
						levelId: 7,
						type: 'WORD_PICKER',
						question: 'Мы были молоды и беспечны',
						correctAnswer: 'We were young and reckless',
						options: ['were', 'reckless', 'We', 'young', 'and'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 16,
						levelId: 7,
						type: 'TEXT_INPUT',
						question: 'Ты был занят вчера?',
						correctAnswer: 'Were you busy yesterday?',
						options: [],
						partialAnswer: ['', 'yesterday?'],
						order: 2,
					},
					{
						id: 17,
						levelId: 8,
						type: 'WORD_PICKER',
						question: 'Она не работала за границей',
						correctAnswer: 'She did not work abroad',
						options: ['abroad', 'She', 'work', 'did', 'not'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 18,
						levelId: 8,
						type: 'WORD_PICKER',
						question: 'Они не были дома вчера',
						correctAnswer: 'They were not at home yesterday',
						options: ['yesterday', 'were', 'They', 'at', 'home', 'not'],
						partialAnswer: [],
						order: 2,
					},
					{
						id: 19,
						levelId: 9,
						type: 'TEXT_INPUT',
						question: 'Я не была злой вчера',
						correctAnswer: 'I was not angry yesterday',
						options: [],
						partialAnswer: ['I', 'yesterday'],
						order: 1,
					},
					{
						id: 20,
						levelId: 9,
						type: 'TEXT_INPUT',
						question: 'Я был уставшим',
						correctAnswer: 'I was tired',
						options: [],
						partialAnswer: ['', ''],
						order: 2,
					},
					{
						id: 21,
						levelId: 10,
						type: 'WORD_PICKER',
						question: 'Где были твои родители прошлым летом?',
						correctAnswer: 'Where were your parents last summer?',
						options: ['summer?', 'parents', 'Where', 'were', 'your', 'last'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 22,
						levelId: 10,
						type: 'TEXT_INPUT',
						question: 'Она работала за границей два года назад',
						correctAnswer: 'She worked abroad 2 years ago',
						options: [],
						partialAnswer: ['She', '2 years ago'],
						order: 2,
					},
					{
						id: 23,
						levelId: 10,
						type: 'WORD_PICKER',
						question: 'Вчера я встретил своего старого друга',
						correctAnswer: 'I met my old friend yesterday',
						options: ['my', 'met', 'I', 'yesterday', 'friend', 'old'],
						partialAnswer: [],
						order: 3,
					},
					// SECTION FUTURE SIMPLE RU EN
					{
						id: 24,
						levelId: 11,
						type: 'WORD_PICKER',
						question: 'Мой муж купит мне это кольцо',
						correctAnswer: 'My husband will buy this ring for me',
						options: ['will', 'My', 'this', 'husband', 'me', 'buy', 'ring', 'for'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 25,
						levelId: 11,
						type: 'TEXT_INPUT',
						question: 'На следующей неделе я пойду в кино',
						correctAnswer: 'I will go to the cinema next week',
						options: [],
						partialAnswer: ['I', 'next week'],
						order: 2,
					},
					{
						id: 26,
						levelId: 11,
						type: 'WORD_PICKER',
						question: 'Я не пойду завтра на прогулку',
						correctAnswer: 'I will not go for a walk tomorrow',
						options: ['will', 'not', 'I', 'for', 'go', 'tomorrow', 'a', 'walk'],
						partialAnswer: [],
						order: 3,
					},
					{
						id: 27,
						levelId: 12,
						type: 'WORD_PICKER',
						question: 'Мы не найдем твой ключ завтра',
						correctAnswer: 'We will not find your key tomorrow',
						options: ['will', 'find', 'We', 'key', 'not', 'tomorrow', 'your'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 28,
						levelId: 12,
						type: 'TEXT_INPUT',
						question: 'Я не буду там работать',
						correctAnswer: 'I will not work there',
						options: [],
						partialAnswer: ['I', 'there'],
						order: 2,
					},
					{
						id: 29,
						levelId: 13,
						type: 'WORD_PICKER',
						question: 'Я пойду завтра на прогулку?',
						correctAnswer: 'Will I go for a walk tomorrow?',
						options: ['for', 'go', 'Will', 'a', 'I', 'tomorrow?', 'walk'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 30,
						levelId: 13,
						type: 'TEXT_INPUT',
						question: 'Мы найдем твой ключ завтра?',
						correctAnswer: 'Will we find your key tomorrow?',
						options: [],
						partialAnswer: ['', 'tomorrow'],
						order: 2,
					},
					{
						id: 31,
						levelId: 14,
						type: 'WORD_PICKER',
						question: 'Куда я завтра пойду?',
						correctAnswer: 'Where will I go tomorrow?',
						options: ['will', 'I', 'Where', 'go', 'tomorrow'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 32,
						levelId: 14,
						type: 'WORD_PICKER',
						question: 'Я думаю, он выиграет это состязание',
						correctAnswer: 'I think he will win this competition',
						options: ['think', 'will', 'I', 'competition', 'he', 'this', 'win'],
						partialAnswer: [],
						order: 2,
					},
					{
						id: 33,
						levelId: 15,
						type: 'TEXT_INPUT',
						question: 'Завтра будет сильный шторм',
						correctAnswer: 'The great storm will be tomorrow',
						options: [],
						partialAnswer: ['The great storm', ''],
						order: 1,
					},
					{
						id: 34,
						levelId: 15,
						type: 'WORD_PICKER',
						question: 'Я покрашу этот стол',
						correctAnswer: 'I will paint this table',
						options: ['paint', 'will', 'I', 'this', 'table'],
						partialAnswer: [],
						order: 2,
					},
					// SECTION Präsens RU GE
					{
						id: 35,
						levelId: 16,
						type: 'WORD_PICKER',
						question: 'Я читаю книгу',
						correctAnswer: 'Ich lese das Buch',
						options: ['Ich', 'das', 'lese', 'Buch'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 36,
						levelId: 17,
						type: 'TEXT_INPUT',
						question: 'Мы учим немецкий',
						correctAnswer: 'Wir lernen Deutsch',
						options: [],
						partialAnswer: ['Wir', 'Deutsch'],
						order: 1,
					},
					{
						id: 37,
						levelId: 18,
						type: 'WORD_PICKER',
						question: 'Она работает в школе',
						correctAnswer: 'Sie arbeitet in der Schule',
						options: ['der', 'Schule', 'in', 'Sie', 'arbeitet'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 38,
						levelId: 19,
						type: 'TEXT_INPUT',
						question: 'Ты пьёшь кофе утром',
						correctAnswer: 'Du trinkst Kaffee am Morgen',
						options: [],
						partialAnswer: ['Du', 'Kaffee am Morgen'],
						order: 1,
					},
					{
						id: 39,
						levelId: 20,
						type: 'TEXT_INPUT',
						question: 'Они живут в Берлине',
						correctAnswer: 'Sie wohnen in Berlin',
						options: [],
						partialAnswer: ['Sie', 'in Berlin'],
						order: 1,
					},
					// SECTION Präteritum RU GE
					{
						id: 40,
						levelId: 21,
						type: 'WORD_PICKER',
						question: 'Вчера я смотрел фильм',
						correctAnswer: 'Gestern sah ich einen Film',
						options: ['einen', 'Film', 'Gestern', 'ich', 'sah'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 41,
						levelId: 22,
						type: 'TEXT_INPUT',
						question: 'Мы гуляли в парке',
						correctAnswer: 'Wir spazierten im Park',
						options: [],
						partialAnswer: ['Wir', 'im Park'],
						order: 1,
					},
					{
						id: 42,
						levelId: 23,
						type: 'WORD_PICKER',
						question: 'Она купила новое платье',
						correctAnswer: 'Sie kaufte ein neues Kleid',
						options: ['Sie', 'Kleid', 'neues', 'kaufte', 'ein'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 43,
						levelId: 24,
						type: 'TEXT_INPUT',
						question: 'Ты вчера работал?',
						correctAnswer: 'Arbeitetest du gestern?',
						options: [],
						partialAnswer: ['', 'du gestern?'],
						order: 1,
					},
					{
						id: 44,
						levelId: 25,
						type: 'TEXT_INPUT',
						question: 'Они приехали в 8 часов',
						correctAnswer: 'Sie kamen um 8 Uhr an',
						options: [],
						partialAnswer: ['Sie', 'um 8 Uhr an'],
						order: 1,
					},
					// SECTION Présent RU FR
					{
						id: 45,
						levelId: 26,
						type: 'WORD_PICKER',
						question: 'Я говорю по-французски',
						correctAnswer: 'Je parle français',
						options: ['Je', 'parle', 'français'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 46,
						levelId: 26,
						type: 'TEXT_INPUT',
						question: 'Мы живём в Париже',
						correctAnswer: 'Nous habitons à Paris',
						options: [],
						partialAnswer: ['Nous', 'à Paris'],
						order: 2,
					},
					{
						id: 47,
						levelId: 27,
						type: 'WORD_PICKER',
						question: 'Ты работаешь в школе',
						correctAnswer: "Tu travailles à l'école",
						options: ['Tu', 'travailles', 'à', "l'école"],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 48,
						levelId: 27,
						type: 'TEXT_INPUT',
						question: 'Она читает книгу',
						correctAnswer: 'Elle lit un livre',
						options: [],
						partialAnswer: ['Elle', 'un livre'],
						order: 2,
					},
					{
						id: 49,
						levelId: 28,
						type: 'WORD_PICKER',
						question: 'Я не понимаю',
						correctAnswer: 'Je ne comprends pas',
						options: ['Je', 'ne', 'comprends', 'pas'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 50,
						levelId: 28,
						type: 'TEXT_INPUT',
						question: 'Вы не говорите по-английски',
						correctAnswer: 'Vous ne parlez pas anglais',
						options: [],
						partialAnswer: ['Vous', 'pas anglais'],
						order: 2,
					},
					{
						id: 51,
						levelId: 29,
						type: 'WORD_PICKER',
						question: 'Где ты живёшь?',
						correctAnswer: 'Où habites-tu?',
						options: ['Où', 'habites-tu?'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 52,
						levelId: 29,
						type: 'TEXT_INPUT',
						question: 'Что ты делаешь?',
						correctAnswer: "Qu'est-ce que tu fais?",
						options: [],
						partialAnswer: ["Qu'est-ce que", 'tu fais?'],
						order: 2,
					},
					{
						id: 53,
						levelId: 30,
						type: 'WORD_PICKER',
						question: 'Мне нравится французская кухня',
						correctAnswer: "J'aime la cuisine française",
						options: ["J'aime", 'la', 'cuisine', 'française'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 54,
						levelId: 30,
						type: 'TEXT_INPUT',
						question: 'Они учатся в университете',
						correctAnswer: "Ils étudient à l'université",
						options: [],
						partialAnswer: ['Ils', "à l'université"],
						order: 2,
					},
					// SECTION Präsens EN GE
					{
						id: 55,
						levelId: 31,
						type: 'WORD_PICKER',
						question: 'I learn German quickly',
						correctAnswer: 'Ich lerne schnell Deutsch',
						options: ['schnell', 'Ich', 'Deutsch', 'lerne'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 56,
						levelId: 32,
						type: 'TEXT_INPUT',
						question: 'We live near the station',
						correctAnswer: 'Wir wohnen nahe dem Bahnhof',
						options: [],
						partialAnswer: ['Wir', 'nahe dem Bahnhof'],
						order: 1,
					},
					{
						id: 57,
						levelId: 33,
						type: 'WORD_PICKER',
						question: 'She drinks tea with milk',
						correctAnswer: 'Sie trinkt Tee mit Milch',
						options: ['Sie', 'Milch', 'Tee', 'mit', 'trinkt'],
						partialAnswer: [],
						order: 1,
					},
					{
						id: 58,
						levelId: 34,
						type: 'TEXT_INPUT',
						question: 'You speak very clearly',
						correctAnswer: 'Du sprichst sehr deutlich',
						options: [],
						partialAnswer: ['Du', 'sehr deutlich'],
						order: 1,
					},
					{
						id: 59,
						levelId: 35,
						type: 'WORD_PICKER',
						question: 'I learn German quickly',
						correctAnswer: 'Ich lerne schnell Deutsch',
						options: ['Deutsch', 'schnell', 'lerne', 'Ich'],
						partialAnswer: [],
						order: 1,
					},
				],
			})
		})
		console.log('Database seeding completed successfully!')
	} catch (error) {
		console.error('Error during database seeding:', error)
	}
}

main()
	.catch(e => {
		console.error(e)
		process.exit(1)
	})
	.finally(() => {
		prisma.$disconnect()
	})
